### PR TITLE
A way of using ipy_island based on ipyparallel

### PR DESCRIPTION
**Pull request by dwgoon**
The existing `ipy_island` depends on `IPython.kernel.TaskClient` and `MapTask`, which are deprecated, and even not available in the recent ipython support. Therefore, the following warning message can be encountered.

```
.../lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: 
The `IPython.kernel` package has been deprecated.
You should import from ipykernel or jupyter_client instead. 
```

I modified this part based on `ipyparallel`, which provides `ipyparallel.Client` and `View` for the ipython multiprocessing. Review my commit to check whether it is appropriate, please.

### CODE REVIEW

**Comment by darioizzo** [comment]
Thnaks, the travis CI is broken, but the problem is on our side. Will review this soon....

**Comment by dwgoon** [comment]
I hope it will work! Thanks :)

**Comment by dwgoon** [comment]
`--user` option for pip solved the travis CI test.

**Comment by darioizzo** [comment]
Great thanks !!

**Comment by darioizzo** [comment]
We have quickly reviewed this. As this PaGMO code base is only in maintenance mode (we are working on the new PaGMO code base), we are not going to test your solution thoroughly, but will merge into master as it solves the warning issue and possibly reintroduces a working ipython island. Will merge when Travis passes

**Comment by darioizzo** [comment]
merged

**Comment by dwgoon** [comment]
Thanks for your review and merge 👍

**Pull request merged**
