### PR TITLE
Unit-Test Decomposition-weighted

### PR DESCRIPTION
**Pull request by SunilMahendrakar**
Unit-Test Decompose(weighted). @kiryx Please take a look.

### CODE REVIEW

**Comment by SunilMahendrakar** [comment]
@kiryx please take a look.

**Comment by SunilMahendrakar** [comment]
@kiryx I have added zdt and dtlz(all variants) to the test code. Please take a look.

**Comment by darioizzo** [comment]
Can you add some comment explaining what exactly the test is about? What is it that it checks?

**Comment by SunilMahendrakar** [comment]
Sure!

**Comment by SunilMahendrakar** [comment]
@darioizzo done. Please take a look. :)

**Comment by darioizzo** [comment]
1) weights should be fitness_vector, not decision_vector tpye
2) random numbers should be generated using boost not rand()

**Comment by SunilMahendrakar** [comment]
@darioizzo okay. my bad. fixing it.

**Comment by SunilMahendrakar** [comment]
@darioizzo done :)

**Comment by SunilMahendrakar** [comment]
@darioizzo I've rebased(resolved the conflicts) and merged all the commits into one. good to go :)

**Pull request merged**
