### PR TITLE
Edge top migr

### PR DESCRIPTION
**Pull request by kiryx**
First patch adds the C++/Python interface for new per-edge migration probability.
Second patch removes all the island-based migration probability.
Last patch is mainly docs and minor comment fixes.

This patch adresses the issue #80

### CODE REVIEW

**Comment by kiryx** [comment]
I skipped the algorithm.null() and problem.identity() test so far, but I think it should go here (or in separate patch). Should I add the problem.identity() and add it to this pull request ?

**Comment by darioizzo** [comment]
yep thanks

**Comment by darioizzo** [comment]
Are you still working on this or I should check it in its current state?

**Comment by kiryx** [comment]
I had to drop some tests because of this undefined behaviour in evolve_batch.
I think you can check it out now.

**Pull request merged**
