### PR TITLE
Allow changes to distribution_type once an archipelago has been created.

### LINKED ISSUE #108: Setting archipelago.distribution_type by property does not work
In PyGMO, the archipelago distribution type (broadcast, point_to_point) can be either set in constructor:

```Python
from PyGMO import archipelago, distribution_type

archi = archipelago(... , distribution_type=distribution_type.broadcast)
```
or as a property (at least there is interface for it!):

```Python
archi = archipelago(..)
archi.distribution_type = distribution_type.broadcast
```

The latter does not work, as the code always executes the point_to_point (default) distribution case.
**I haven't checked, but the same issue may occur for archipelago.migration_direction**

### PR DESCRIPTION
**Pull request by jdiez17**
Fixes #108. cc @kiryx 

Added tests in PaGMO and PyGMO.

:rocket:

### CODE REVIEW

**Comment by jdiez17** [comment]
Note about the Travis failure: there seems to be an intermittent failure when trying to link the PyGMO libraries with libpython2.7.a. This failure can be safely ignored; PR is safe to merge. However maybe we should disable building PyGMO in Travis until we're sure we've fixed the problem. @darioizzo thoughts?

**Comment by kiryx** [comment]
Functionally it looks good, I would suggest some naming changes though:

1. c++ test file should be named "test_archipelago.cpp", in it the unit test file should be named "test_distribution_type"
1. Python test should be named "_archipelago_tests.py", and should contain the ArchipelagoTests class as you suggested. As you probably noticed there's also ``ArchipelagoTests`` class in ``_topology_tests.py`` file [here](https://github.com/esa/pagmo/blob/master/PyGMO/test/_topology_tests.py#L5), I suggest you merge those tests together into your ``ArchipelagoTests`` class in ``_archipelago_tests.py`` (remove the ``ArchipelagoTests`` class from ``_topology_tests.py``)

**Comment by jdiez17** [comment]
Okay, I'll implement your changes. The idea behind this naming scheme was to have all of the property unit tests segregated into their own suite, but I guess it makes more sense to have these in a test suite that tests a specific class. Agreed on refactoring `ArchipelagoTests` from `_topology_tests.py` and `_property_tests.py` into `_archipelago_tests.py`.

**Comment by jdiez17** [comment]
@kiryx Implemented your naming scheme changes.

    >>> run_archipelago_test_suite()
    test_distribution_type (PyGMO.test._archipelago_tests.ArchipelagoTests)
    Testing whether the distribution_type property works ... ok
    test_one_way_ring_null_alg (PyGMO.test._archipelago_tests.ArchipelagoTests) ... ok
    test_simple_probs (PyGMO.test._archipelago_tests.ArchipelagoTests)
    Testing whether migration history matches the expected output for each migration_direction and distribution_type ... ok

**Pull request merged**
